In [1]:
#All Operations in numpy is in array form
#numpy deals with N-dimensional arrays
#1st form  
import numpy as np
my_list = [1,2,3,4,5,6]
    
type(np.array(my_list))

arr = np.array(my_list)

arr

array([1, 2, 3, 4, 5, 6])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,5)) #Arrays in ones form

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#2nd form
import numpy as np



arr = np.array([21,23,24,25])

arr

np.zeros((20,5)) #Array in Zeros form

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.random.randint(0,10)   # Generate Random Numbers

5

In [19]:
np.random.randint(0,1000,(4,4))   #Generates Random numbers from 0-1000 in 4*4 array

array([[290, 633, 273, 977],
       [638, 984, 670, 179],
       [816, 813, 619,  27],
       [385, 391, 624, 916]])

In [16]:
np.random.seed(101)       #Generates Constant value(To stop random value generating)

arr1 = np.random.randint(0,100,10)

arr1


array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [17]:
arr1.max()        #Gives Maximum value from the array
arr1.min()        #Gives Miniimum value from the array
arr1.mean()       #Gives Mean(Average) value from the array
arr1.argmax()     #Gives Maximum value Index number from the array
arr1.argmin()     #Gives Miniimum value index number from the array
arr1.reshape(2,5) #Reshape the array in given rows and colunms format

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [47]:
mat = np.arange(0,100).reshape(10,10) #It arrange the array in 10*10 format
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat[7,1]
mat[0,:] #row slicing
mat[:,0] #col slicing

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
import numpy as np

ops = [21,27,18,1996,1991,1963]

arrs = np.array(ops)

arrs

np.arange(1,10,2)
np.zeros((3,5))
np.ones((2,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
import numpy as np

op = []

arrr = np.array(op)

arrr

np.arange(1,100,10)
np.zeros((3,5))
np.ones((2,5))
np.random.randint(0,1000,(4,4))







array([[309,  29, 666, 816],
       [344, 481, 382, 655],
       [275, 257, 173, 728],
       [683,  37, 239,  21]])

In [14]:
np.random.seed(101)

ar = np.random.randint(0,100,10)

ar

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])