In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\swaps\\ML-Python Stuffs\\Edwisor_Assignments'

In [4]:
import numpy as np

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
lis = ["India", 5, 6,7]

In [10]:
sample_matrix = np.matrix('1 2 3; 3 4 5 ')

In [12]:
sample_matrix

matrix([[1, 2, 3],
        [3, 4, 5]])

In [13]:
np.transpose(sample_matrix)

matrix([[1, 3],
        [2, 4],
        [3, 5]])

In [16]:
import pandas as pd
df = pd.DataFrame({'age':[1,2,4,9],
                   'Gender':["M", "F","F","M"],
                    'Income': [5,6,7,3]})

In [17]:
df

age Gender  Income
0    1      M       5
1    2      F       6
2    4      F       7
3    9      M       3