In [1]:
import numpy as np

In [2]:
# python List
my_list = [[1,2,3],[3,2,1]]

In [3]:
np.array(my_list)

array([[1, 2, 3],
       [3, 2, 1]])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


# Built-in Methods
There are lots of built-in ways to generate Arrays

# arange
Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((1,2))

array([[1., 1.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [22]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

# eye
Creates an identity matrix

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random
Numpy also has lots of ways to create random number arrays:
# rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [27]:
np.random.randint(0,100)

82

In [29]:
np.random.randint(5)

0

In [31]:
np.random.rand(5,5)

array([[0.73668679, 0.11774532, 0.16268677, 0.99399623, 0.21972197],
       [0.11782574, 0.61798623, 0.17776873, 0.77747549, 0.22424577],
       [0.57883316, 0.61318802, 0.20461297, 0.0396366 , 0.97483123],
       [0.27059408, 0.6809252 , 0.55337781, 0.58313956, 0.30833336],
       [0.8342612 , 0.49303574, 0.60843602, 0.59834098, 0.94843946]])

# randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [33]:
np.random.randn(3)

array([-0.62580701, -1.84301435, -0.54441831])

In [34]:
np.random.randn(5,5)

array([[ 0.85863571, -0.78363575, -0.54923758, -0.41800861,  0.27685408],
       [-0.56541301, -1.56526768, -0.8575367 , -0.35699416, -0.89679994],
       [-1.61109013,  0.31655051, -0.29102249,  2.05113023,  0.24408513],
       [-0.22477427, -0.43035282,  1.12577821,  0.66934166, -0.417487  ],
       [-0.25621405, -0.0781599 , -0.66031994, -0.10507776, -1.93117262]])

# randint
Return random integers from low (inclusive) to high (exclusive).

In [37]:
np.random.randint(1,150)

149

In [39]:
np.random.randint(1,100,10)

array([81, 77, 11, 60, 24, 93, 92, 11, 78, 99])

# Array Attributes and Methods
Let's discuss some useful attributes and methods or an array:
In [22]:


In [41]:
arr = np.arange(24)
ranarr = np.random.randint(0,100,10)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
ranarr

array([60, 98, 39, 29, 33, 67, 31, 44, 30, 33])

# Reshape
Returns an array containing the same data with a new shape.

In [48]:
arr.reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [50]:
ranarr

array([60, 98, 39, 29, 33, 67, 31, 44, 30, 33])

In [52]:
ranarr.max()

98

In [55]:
ranarr.argmax()

1

In [57]:
ranarr.min()

29

In [59]:
ranarr.argmin()

3

# Shape
Shape is an attribute that arrays have (not a method):

In [62]:
arr.shape

(24,)

In [64]:
arr.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [66]:
arr.reshape(1,24).shape

(1, 24)

In [68]:
arr.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [70]:
arr.reshape(24,1).shape


(24, 1)

# dtype

You can also grab the data type of the object in the array:

In [71]:
arr.dtype

dtype('int32')